services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./backend/staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - mmpi-network

  frontend:
    build:
      context: ./frontend/mmpi-test
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    networks:
      - mmpi-network
    environment:
      - NODE_ENV=production

  postgres:
    image: postgres:13.3
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mmpi-network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./backend/staticfiles:/app/staticfiles
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - mmpi-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - mmpi-network
    restart: unless-stopped

volumes:
  postgres-data:
  redis-data:

networks:
  mmpi-network:
    driver: bridge
