version: "2.29.2"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "MMPI"
      POSTGRES_USER: "Admin"
      POSTGRES_PASSWORD: "test_mmpi_admin"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Admin -d MMPI"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

volumes:
  habrdb-data: