version: '3.8'

services:
  app:
    image: mmpi-test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/src
    environment:
      - NODE_ENV=development
    command: npm run dev
