services:
  app:
    image: mmpi-test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    networks:
      - mmpi-network

networks:
  mmpi-network:
    driver: bridge
    external: true