# Generated by Django 5.1.7 on 2025-05-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Dal", "0001_initial"),
    ]

    operations = []
