# Generated by Django 5.1.7 on 2025-04-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dal', '0002_alter_useranswer_вопрос_1_alter_useranswer_вопрос_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
