# Generated by Django 5.1.7 on 2025-05-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dal", "0002_auto_20250509_2134"),
    ]

    operations = [
        migrations.CreateModel(
            name="TScoreFormula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("Мужской", "Мужской"), ("Женский", "Женский")],
                        max_length=7,
                    ),
                ),
                ("scale", models.CharField(max_length=5)),
                ("M", models.FloatField()),
                ("delta", models.FloatField()),
            ],
            options={
                "unique_together": {("sex", "scale")},
            },
        ),
    ]
