# Generated by Django 5.1.7 on 2025-05-09 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dal", "0003_tscoreformula"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scale", models.CharField(max_length=5)),
                ("M", models.FloatField()),
                ("delta", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tscore_settings",
                        to="Dal.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "scale")},
            },
        ),
        migrations.DeleteModel(
            name="TScoreFormula",
        ),
    ]
