# Generated by Django 5.1.7 on 2025-05-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dal", "0004_usertscore_delete_tscoreformula"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertscore",
            name="T",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
