# Generated by Django 5.1.7 on 2025-05-09 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Dal", "0005_usertscore_t"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertscore",
            name="T",
        ),
    ]
