# Generated by Django 5.1.7 on 2025-04-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dal", "0005_remove_user_id_user_user_id_alter_user_django_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
    ]
