# Generated by Django 5.1.7 on 2025-05-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dal", "0007_usertscore_t"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertscore",
            name="original_T",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
