# Generated by Django 5.1.7 on 2025-05-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dal", "0008_usertscore_original_t"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertscore",
            name="original_M",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usertscore",
            name="original_delta",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
