# Generated by Django 5.1.7 on 2025-04-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dal", "0008_alter_user_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.PositiveIntegerField(editable=False, null=True, unique=True),
        ),
    ]
