# Generated by Django 5.1.7 on 2025-05-16 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Dal", "0009_usertscore_original_m_usertscore_original_delta"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Результат пользователя",
                "verbose_name_plural": "Результаты пользователей",
            },
        ),
        migrations.AlterModelOptions(
            name="useranswer",
            options={
                "verbose_name": "Вопросы и ответы",
                "verbose_name_plural": "Вопросы и ответы",
            },
        ),
    ]
