# Generated by Django 5.1.7 on 2025-04-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dal", "0009_alter_user_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.PositiveIntegerField(default=0, editable=False, unique=True),
        ),
    ]
