# Generated by Django 5.1.7 on 2025-04-26 09:20

from django.db import migrations

def set_user_id(apps, schema_editor):
    User = apps.get_model('Dal', 'User')
    for user in User.objects.filter(user_id__isnull=True):
        user.user_id = user.django_user_id
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ("Dal", "0010_alter_user_user_id"),
    ]

    operations = [
        migrations.RunPython(set_user_id),
    ]
